# Generated by Django 3.2.9 on 2022-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_superuser', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
