# Generated by Django 3.2.9 on 2023-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('is_superuser', models.BooleanField(default=0)),
                ('can_edit', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Olt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('olt_configuration', models.JSONField()),
            ],
        ),
    ]
