# Generated by Django 3.2.9 on 2023-02-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220211_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
